### ISSUE TITLE
Uncaught Exception: index.spec.js in 1.1.2

### ISSUE THREAD

**Issue by DhruvAerosol** [tonickkozlov/vue-tweet-embed#4]
Uncaught Exception: index.spec.js
  Error: Couldn't find preset "es2017" relative to directory "E:\\Projects\\vue-
tweet-embed"
    at E:\Projects\vue-tweet-embed\node_modules\babel-core\lib\transformation\fi
le\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (E:\Projects\vue-tweet-embed\node_modules\ba
bel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\Projects\vue-tweet-embed\node_modules\babe
l-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\Projects\vue-tweet-embed\node_modules\babe
l-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\Projects\vue-tweet-embed\node_modules\babel-core\l
ib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\Projects\vue-tweet-embed\node_modules\babel-core\lib
\transformation\file\index.js:212:65)
    at new File (E:\Projects\vue-tweet-embed\node_modules\babel-core\lib\transfo
rmation\file\index.js:135:24)
    at Pipeline.transform (E:\Projects\vue-tweet-embed\node_modules\babel-core\l
ib\transformation\pipeline.js:46:16)
    at CachingPrecompiler._transform (E:\Projects\vue-tweet-embed\node_modules\a
va\lib\caching-precompiler.js:41:29)
    at transform (E:\Projects\vue-tweet-embed\node_modules\caching-transform\ind
ex.js:43:10)
    at CachingPrecompiler.transform (E:\Projects\vue-tweet-embed\node_modules\ca
ching-transform\index.js:60:17)
    at CachingPrecompiler.precompileFile (E:\Projects\vue-tweet-embed\node_modul
es\ava\lib\caching-precompiler.js:27:9)
    at Api._runFile (E:\Projects\vue-tweet-embed\node_modules\ava\api.js:56:33)
    at resolve (E:\Projects\vue-tweet-embed\node_modules\ava\api.js:237:24)
From previous event:
    at Api._runWithoutPool (E:\Projects\vue-tweet-embed\node_modules\ava\api.js:
234:5)
    at _precompileHelpers.then (E:\Projects\vue-tweet-embed\node_modules\ava\api
.js:161:23)
From previous event:
    at Api._run (E:\Projects\vue-tweet-embed\node_modules\ava\api.js:150:5)
    at AvaFiles.findTestFiles.then.files (E:\Projects\vue-tweet-embed\node_modul
es\ava\api.js:70:24)
From previous event:
    at Api.run (E:\Projects\vue-tweet-embed\node_modules\ava\api.js:70:5)
    at Object.exports.run (E:\Projects\vue-tweet-embed\node_modules\ava\lib\cli.
js:168:7)
    at Object.<anonymous> (E:\Projects\vue-tweet-embed\node_modules\ava\cli.js:2
2:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

  0 tests passed [18:21:14]
  1 uncaught exception

**Comment by tonickkozlov** [comment]
Fixed in 1.1.3. Please re-open if the issue persists

**Comment by tonickkozlov** [comment]
Also this should allow you to fix your PR

**Comment by DhruvAerosol** [comment]
what should i do to fix my PR?

**Comment by tonickkozlov** [comment]
Pulling latest and re-running "npm install" should be sufficient to allow you to build successfully, also to run tests. Your PR is missing tests at the moment, please add them. Thanks!

**Comment by DhruvAerosol** [comment]
What should i add in tests?
i have prepared tests same like given, just changed id '123' to '14' and DOM id 'foo1 => 'bar1' so is it ok?' 
if you not then can you add it i have mentioned in my forked code's ReadME file.
Or guide me how can i add it.

**Comment by tonickkozlov** [comment]
We are talking about this PR https://github.com/tonickkozlov/vue-tweet-embed/pull/5 right? Let's follow up in the PR conversation page
