### ISSUE TITLE
Timeline tweets no more working with vue 3

### ISSUE THREAD

**Issue by ahmedrazaa** [tonickkozlov/vue-tweet-embed#69]
index.js?44d8:90 
        
       Uncaught (in promise) TypeError: h is not a function
    at Proxy.render (webpack-internal:///./node_modules/vue-tweet-embed/dist/core/index.js:90:14)
    at renderComponentRoot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:1050:44)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5167:57)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:203:25)
    at setupRenderEffect (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5293:9)
    at mountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5076:9)
    at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5034:17)
    at patch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4635:21)
    at mountChildren (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4822:13)
    at mountElement (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4731:17)

**Comment by jacksongross** [comment]
I've opened a PR to make it Vue 3 compatible -- https://github.com/tonickkozlov/vue-tweet-embed/pull/72

**Comment by jacksongross** [comment]
I've published a fork that's Vue 3 compatible as there doesn't seem to be much activity here. https://github.com/jacksonGross/vue-tweet-embed

**Comment by ivryb** [comment]
@jacksongross Man you're just awesome! Thank you very much!
